import type { WholeBookPreflightPageModel } from "./preflight";
import type { WholeBookResultEnvelope } from "./resultEnvelope";
import type { WholeBookEvidenceRefDto } from "./evidence";
import type { NarrativeStructureMapProjectionDto } from "./structureMap";
import type { ConflictCenterItemDto } from "./conflictCenter";
import type { NarrativeReviewActionRequest } from "./review";
import type { WholeBookRunViewState } from "./runView";
import { RESULT_ENVELOPE_SCHEMA, RESULT_ENVELOPE_VERSION } from "./resultEnvelope";
import { STRUCTURE_MAP_PROJECTION_SCHEMA } from "./structureMap";

export const FIXTURE_PREFLIGHT: WholeBookPreflightPageModel = {
  book: {
    book_id: 1,
    title: "Sample Book",
    chapter_count: 10,
    paragraph_count: 100,
    character_count: 50000,
    current_snapshot_id: 11,
    snapshot_created_at: "2026-07-23T00:00:00Z",
    body_changed_since_snapshot: false,
    snapshot_rebuild_required: false,
  },
  snapshot: {
    snapshot_id: 11,
    status: "completed",
    created_at: "2026-07-23T00:00:00Z",
    chapter_count: 10,
    paragraph_count: 100,
    character_count: 50000,
    integrity_ok: true,
  },
  capability: {
    capability_key: "whole_book_analysis",
    allowed: false,
    reason_code: "CAPABILITY_NOT_SHIPPED",
    availability: "unavailable",
    message: "not shipped",
  },
  quota: {
    allowed: true,
    reason_code: "",
    remaining: {},
    estimated_usage: {},
  },
  engine: {
    engine_id: null,
    available: false,
    supports_mode: true,
    message: "no production engine",
  },
  analysis_mode: "whole_book_native",
  requested_modules: ["book_overview"],
  resolved_modules: ["book_overview"],
  stage_plan: [
    {
      stage_key: "build_fulltext_index",
      display_name: "Build fulltext index",
      order: 10,
      required: true,
      estimated_cost_class: "low",
      produced_module_keys: ["book_overview"],
    },
  ],
  source_coverage: {
    fulltext_snapshot_ready: true,
    enhanced_asset_coverage_ratio: null,
    scene_coverage_ratio: null,
    reader_journey_coverage_ratio: null,
    chapter_analysis_coverage_ratio: null,
    enhanced_degraded: false,
  },
  estimated_usage: {
    estimated_token_input: null,
    estimated_token_output: null,
    estimated_cost: null,
    estimated_duration_class: "unknown",
    currency: "USD",
  },
  blocking_reasons: ["WHOLE_BOOK_RUNS_ENDPOINT_DISABLED=true"],
  warnings: [],
  run_creation_enabled: false,
  confirmation_required: true,
  auto_fill_notes: ["module book_overview requires stages: build_fulltext_index"],
  force_start_allowed: false,
};

export const FIXTURE_RUN_VIEW: WholeBookRunViewState = {
  run_id: 101,
  book_id: 1,
  snapshot_id: 11,
  analysis_mode: "whole_book_native",
  status: "running",
  current_stage: "analyze_structure",
  stages: [],
  completed_modules: ["book_overview"],
  available_modules: ["book_overview", "structure_stages"],
  failed_modules: [],
  partial_results_available: true,
  progress_percent: null,
  token_usage: {},
  cost: null,
  started_at: "2026-07-23T01:00:00Z",
  updated_at: "2026-07-23T01:05:00Z",
  estimated_remaining: null,
  blocking_issue: null,
  allowed_actions: ["pause", "cancel", "view_partial_results"],
  module_statuses: {
    book_overview: "completed",
    structure_stages: "running",
  },
};

export const FIXTURE_RESULT_ENVELOPE: WholeBookResultEnvelope = {
  schema: RESULT_ENVELOPE_SCHEMA,
  version: RESULT_ENVELOPE_VERSION,
  run_id: 101,
  book_id: 1,
  book_snapshot_id: 11,
  analysis_mode: "whole_book_native",
  module_key: "book_overview",
  module_status: "partial",
  generated_at: "2026-07-23T01:05:00Z",
  source_stage_keys: ["build_fulltext_index"],
  source_artifact_ids: [],
  asset_ids: [],
  asset_version_ids: [],
  relation_ids: [],
  relation_version_ids: [],
  conflict_ids: [],
  evidence_count: 0,
  confidence_summary: { mean: null, min: null, max: null, labeled_counts: {} },
  review_summary: {
    candidate_count: 0,
    confirmed_count: 0,
    corrected_count: 0,
    rejected_count: 0,
    locked_count: 0,
    conflict_count: 0,
  },
  stale: false,
  partial: true,
  warnings: [],
  payload: {
    logline: "",
    premise: "",
    central_question: "",
    primary_conflict: "",
    protagonist_asset_id: null,
    major_storyline_ids: [],
    structure_summary: "",
    ending_state: "",
    evidence_refs: [],
    confidence: null,
  },
};

export const FIXTURE_EVIDENCE: WholeBookEvidenceRefDto = {
  evidence_id: 1,
  evidence_type: "asset_evidence",
  book_snapshot_id: 11,
  snapshot_chapter_id: 1,
  snapshot_paragraph_id: 1,
  source_chapter_id: 1,
  source_scene_id: null,
  stable_paragraph_id: "p-1",
  paragraph_content_hash: "abc",
  start_offset: 0,
  end_offset: 10,
  evidence_role: "support",
  evidence_label: "support",
  chapter_title: "Ch1",
  paragraph_preview: "short",
  deep_link: "storylens://book/1/chapter/1/paragraph/1",
  integrity_status: "valid",
};

export const FIXTURE_REVIEW_ACTION: NarrativeReviewActionRequest = {
  action: "confirm",
  target_type: "asset_version",
  target_id: "42",
  expected_version: 3,
  actor: "user",
  correction_payload: {},
  evidence_changes: [],
  resolution_payload: {},
  reason: null,
  idempotency_key: "idem-1",
};

export const FIXTURE_CONFLICT: ConflictCenterItemDto = {
  conflict_id: 9,
  conflict_type: "locked_asset_vs_new_run",
  severity: "blocking",
  status: "open",
  left_ref: { ref_type: "asset_version", ref_id: "1", label: "old", version: 1 },
  right_ref: { ref_type: "asset_version", ref_id: "2", label: "new", version: 2 },
  description: "locked vs candidate",
  affected_modules: ["characters"],
  affected_chapters: [1],
  evidence_refs: [FIXTURE_EVIDENCE],
  created_at: "2026-07-23T02:00:00Z",
  resolution: null,
  allowed_actions: ["resolve_conflict", "dismiss_conflict"],
  defer_allowed: true,
};

export const FIXTURE_STRUCTURE_MAP: NarrativeStructureMapProjectionDto = {
  schema: STRUCTURE_MAP_PROJECTION_SCHEMA,
  book_id: 1,
  book_snapshot_id: 11,
  source_run_id: 101,
  projection_version: "1",
  root_nodes: [],
  edges: [],
  filters: {
    view_mode: "structure_stages",
    search_query: "",
    include_candidates: false,
    max_nodes: 100,
    max_edges: 250,
    theme: "system",
  },
  evidence_index: {},
  review_summary: {},
  conflict_summary: {},
  generated_at: "2026-07-23T02:00:00Z",
};
