"""Frozen error codes for Narrative Intelligence Core (Phase 1P)."""

from __future__ import annotations

from enum import StrEnum


class NarrativeCoreErrorCode(StrEnum):
    MIGRATION_CHECKSUM_MISMATCH = "MIGRATION_CHECKSUM_MISMATCH"
    MIGRATION_BASELINE_INVALID = "MIGRATION_BASELINE_INVALID"
    SNAPSHOT_NOT_FOUND = "SNAPSHOT_NOT_FOUND"
    SNAPSHOT_NOT_COMPLETED = "SNAPSHOT_NOT_COMPLETED"
    SNAPSHOT_BOOK_MISMATCH = "SNAPSHOT_BOOK_MISMATCH"
    SNAPSHOT_INTEGRITY_FAILED = "SNAPSHOT_INTEGRITY_FAILED"
    INVALID_RUN_SCOPE = "INVALID_RUN_SCOPE"
    BOOK_SCOPE_REQUIRES_SNAPSHOT = "BOOK_SCOPE_REQUIRES_SNAPSHOT"
    RANGE_SCOPE_REQUIRES_BOUNDS = "RANGE_SCOPE_REQUIRES_BOUNDS"
    RANGE_SCOPE_INVALID_ORDER = "RANGE_SCOPE_INVALID_ORDER"
    DUPLICATE_STAGE_KEY = "DUPLICATE_STAGE_KEY"
    INVALID_STAGE_TRANSITION = "INVALID_STAGE_TRANSITION"
    COMPLETED_STAGE_CANNOT_RETRY = "COMPLETED_STAGE_CANNOT_RETRY"
    # Phase 1B-P evidence / version / lock (services raise these; Contract freeze)
    ENTITY_NOT_FOUND = "ENTITY_NOT_FOUND"
    ENTITY_LOCKED = "ENTITY_LOCKED"
    ENTITY_INVALID_NAME = "ENTITY_INVALID_NAME"
    ENTITY_NOT_ACTIVE = "ENTITY_NOT_ACTIVE"
    ENTITY_MERGE_NOT_SUPPORTED = "ENTITY_MERGE_NOT_SUPPORTED"
    ALIAS_NOT_FOUND = "ALIAS_NOT_FOUND"
    ALIAS_DUPLICATE = "ALIAS_DUPLICATE"
    ALIAS_LOCKED = "ALIAS_LOCKED"
    ASSET_NOT_FOUND = "ASSET_NOT_FOUND"
    ASSET_LOCKED = "ASSET_LOCKED"
    ASSET_VERSION_NOT_FOUND = "ASSET_VERSION_NOT_FOUND"
    CANONICAL_VERSION_REQUIRED = "CANONICAL_VERSION_REQUIRED"
    REJECTED_CANNOT_BE_CANONICAL = "REJECTED_CANNOT_BE_CANONICAL"
    CANDIDATE_CANNOT_BE_CANONICAL = "CANDIDATE_CANNOT_BE_CANONICAL"
    RELATION_NOT_FOUND = "RELATION_NOT_FOUND"
    RELATION_LOCKED = "RELATION_LOCKED"
    RELATION_VERSION_NOT_FOUND = "RELATION_VERSION_NOT_FOUND"
    EVIDENCE_SNAPSHOT_REQUIRED = "EVIDENCE_SNAPSHOT_REQUIRED"
    EVIDENCE_PARAGRAPH_REQUIRED = "EVIDENCE_PARAGRAPH_REQUIRED"
    EVIDENCE_HASH_MISMATCH = "EVIDENCE_HASH_MISMATCH"
    EVIDENCE_OFFSET_OUT_OF_RANGE = "EVIDENCE_OFFSET_OUT_OF_RANGE"
    EVIDENCE_SNAPSHOT_PARAGRAPH_MISMATCH = "EVIDENCE_SNAPSHOT_PARAGRAPH_MISMATCH"
    CONFLICT_NOT_FOUND = "CONFLICT_NOT_FOUND"
    CONFLICT_ALREADY_CLOSED = "CONFLICT_ALREADY_CLOSED"


class NarrativeCoreError(Exception):
    """Typed error carrying a frozen NarrativeCoreErrorCode."""

    def __init__(self, code: NarrativeCoreErrorCode, message: str = "") -> None:
        self.code = code
        super().__init__(message or code.value)
