/** Private Engine error codes — must match backend PrivateEngineErrorCode. */

export const PRIVATE_ENGINE_ERROR_CODES = [
  "PRIVATE_ENGINE_NOT_FOUND",
  "PRIVATE_ENGINE_SIGNATURE_INVALID",
  "PRIVATE_ENGINE_PROTOCOL_INCOMPATIBLE",
  "PRIVATE_ENGINE_APP_VERSION_INCOMPATIBLE",
  "PRIVATE_ENGINE_HEALTH_FAILED",
  "PROMPT_PACK_NOT_FOUND",
  "PROMPT_PACK_SIGNATURE_INVALID",
  "PROMPT_PACK_INCOMPATIBLE",
  "CONTEXT_BUNDLE_INVALID",
  "CONTEXT_BUNDLE_SNAPSHOT_MISMATCH",
  "CONTEXT_LIMIT_EXCEEDED",
  "MODULE_NOT_SUPPORTED",
  "MODULE_OUTPUT_SCHEMA_INVALID",
  "MODULE_OUTPUT_REFERENCE_INVALID",
  "MODULE_EVIDENCE_INSUFFICIENT",
  "MODULE_EVIDENCE_HASH_MISMATCH",
  "MODULE_OUTPUT_DUPLICATE",
  "MODULE_OUTPUT_CONFLICT",
  "PROVIDER_POLICY_INVALID",
  "PROVIDER_UNAVAILABLE",
  "PROVIDER_TIMEOUT",
  "PROVIDER_CANCELLED",
  "PROVIDER_RESPONSE_INVALID",
  "PROVIDER_BUDGET_EXCEEDED",
  "DATA_HANDLING_CONSENT_REQUIRED",
  "ENGINE_CHECKPOINT_INCOMPATIBLE",
] as const;

export type PrivateEngineErrorCode = (typeof PRIVATE_ENGINE_ERROR_CODES)[number];

export const PRIVATE_ENGINE_ERROR_MESSAGES: Record<PrivateEngineErrorCode, string> = {
  PRIVATE_ENGINE_NOT_FOUND: "Private whole-book engine was not found.",
  PRIVATE_ENGINE_SIGNATURE_INVALID: "Private engine package signature is invalid.",
  PRIVATE_ENGINE_PROTOCOL_INCOMPATIBLE: "Private engine protocol version is incompatible.",
  PRIVATE_ENGINE_APP_VERSION_INCOMPATIBLE: "Private engine is incompatible with this app version.",
  PRIVATE_ENGINE_HEALTH_FAILED: "Private engine health check failed.",
  PROMPT_PACK_NOT_FOUND: "Prompt pack was not found.",
  PROMPT_PACK_SIGNATURE_INVALID: "Prompt pack signature is invalid.",
  PROMPT_PACK_INCOMPATIBLE: "Prompt pack is incompatible with this engine or run.",
  CONTEXT_BUNDLE_INVALID: "Context bundle is invalid or incomplete.",
  CONTEXT_BUNDLE_SNAPSHOT_MISMATCH: "Context bundle does not match the book snapshot.",
  CONTEXT_LIMIT_EXCEEDED: "Context size exceeds the configured limit.",
  MODULE_NOT_SUPPORTED: "Requested whole-book module is not supported.",
  MODULE_OUTPUT_SCHEMA_INVALID: "Module output failed schema validation.",
  MODULE_OUTPUT_REFERENCE_INVALID: "Module output references are invalid.",
  MODULE_EVIDENCE_INSUFFICIENT: "Module output lacks required evidence.",
  MODULE_EVIDENCE_HASH_MISMATCH: "Evidence paragraph hash does not match the snapshot.",
  MODULE_OUTPUT_DUPLICATE: "Module output duplicates an existing candidate.",
  MODULE_OUTPUT_CONFLICT: "Module output conflicts with another candidate.",
  PROVIDER_POLICY_INVALID: "Provider policy is invalid for this request.",
  PROVIDER_UNAVAILABLE: "Provider is unavailable.",
  PROVIDER_TIMEOUT: "Provider request timed out.",
  PROVIDER_CANCELLED: "Provider request was cancelled.",
  PROVIDER_RESPONSE_INVALID: "Provider response is invalid.",
  PROVIDER_BUDGET_EXCEEDED: "Provider budget was exceeded; no candidates were written.",
  DATA_HANDLING_CONSENT_REQUIRED: "User consent is required for this data handling policy.",
  ENGINE_CHECKPOINT_INCOMPATIBLE: "Engine checkpoint is incompatible and cannot be resumed.",
};
