import{describe,expect,it}from"vitest";import{hasScaffoldHeuristic,isRealProviderV2Result,needsReanalysisWarning,parseProgressV2,parseWholeBookV2,sevenModules}from"./adapter";import{V2_PROGRESS_LABELS,V2_PROGRESS_STAGES}from"./contracts";
const ev={evidence_id:"e1",snapshot_id:1,revision_hash:"r",chapter_id:101,chapter_index:1,chapter_title:"一",start_offset:0,end_offset:1,quote_or_excerpt:"x",reason:"support"};
const fixture:any={schema_version:"whole-book-analysis-v2.0",book_metadata:{},type_profile:{},overview:{},story:{structure_stages:[]},characters:{protagonist:{stages:[]}},suspense:{lifecycles:[]},pacing:{points:[]},chapters:{heatmap:[]},assessment:{dimensions:[]},evidence_index:{e1:ev},analysis_metadata:{}};
describe("formal Whole-Book V2 adapter",()=>{it("owns seven modules and validates formal data",()=>{expect(sevenModules).toHaveLength(7);expect(parseWholeBookV2(fixture).evidence_index.e1.chapter_id).toBe(101)});it("rejects mock/legacy payloads",()=>{expect(()=>parseWholeBookV2({...fixture,schema_version:"legacy"})).toThrow();
  // A mismatched map key is still a real inconsistency and still throws.
  expect(()=>parseWholeBookV2({...fixture,evidence_index:{e1:{...ev,evidence_id:"e2"}}})).toThrow()});
it("accepts a book whose chapter ids happen to equal their positions",()=>{
  // The adapter used to reject any evidence row with chapter_id === chapter_index, meaning
  // to catch an ordinal written into an id field. Equality cannot tell that apart from a
  // book whose ids legitimately coincide with their positions, which is the normal case for
  // a freshly imported book: in 深海余烬 the chapters, snapshot chapters and source chapters
  // all run 1..806, so every correct row tripped the rule and the whole report page failed
  // to load. The rule was unsatisfiable, not strict.
  expect(()=>parseWholeBookV2({...fixture,evidence_index:{e1:{...ev,chapter_id:7,chapter_index:7}}})).not.toThrow()});it("validates actionable progress",()=>{expect(parseProgressV2({schema_version:"whole-book-progress-v2.0",overall_percent:42,current_action:"提取窗口"}).current_action).toBe("提取窗口")});it("exposes hierarchical progress stages for formal UI",()=>{expect(V2_PROGRESS_STAGES).toContain("extract_windows");expect(V2_PROGRESS_STAGES).toContain("build_protagonist_arc");expect(V2_PROGRESS_LABELS.extract_windows).toBe("抽取窗口");expect(V2_PROGRESS_LABELS.complete).toBe("完成")});it("defaults missing result_origin to unknown",()=>{const parsed=parseWholeBookV2(fixture);expect(parsed.analysis_metadata.result_origin).toBe("unknown")});it("detects non-real provider and scaffold heuristics",()=>{const real={...fixture,analysis_metadata:{result_origin:"real_provider"},story:{structure_stages:[{stage_id:"s1",chapter_start:1,chapter_end:3,title:"开端",summary:"真实摘要",stage_goal:"g",core_conflict:"c",major_choice:"m",cost_paid:[],gain_received:[],evidence:[]}]},suspense:{lifecycles:[]}};expect(isRealProviderV2Result(parseWholeBookV2(real))).toBe(true);expect(needsReanalysisWarning(parseWholeBookV2(real))).toBe(false);const scaffold={...real,story:{structure_stages:[{stage_id:"s1",chapter_start:1,chapter_end:3,title:"阶段 1",summary:"围绕目标、阻力与选择形成完整阶段",stage_goal:"g",core_conflict:"c",major_choice:"m",cost_paid:[],gain_received:[],evidence:[]}]},suspense:{lifecycles:[{suspense_id:"x",question:"悬念@测试",chapter_start:1,chapter_end:2,status:"open",events:[],payoff:"",evidence:[]}]} };expect(needsReanalysisWarning(parseWholeBookV2(scaffold))).toBe(true);expect(hasScaffoldHeuristic(parseWholeBookV2(scaffold))).toBe(true);const fixtureOrigin={...real,analysis_metadata:{result_origin:"fixture"}};expect(needsReanalysisWarning(parseWholeBookV2(fixtureOrigin))).toBe(true)})});
