# -*- coding: utf-8 -*-
"""Generate core-freeze-manifest.json with sha256 hashes. Read-only of production files."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = Path(__file__).resolve().parent / "core-freeze-manifest.json"

# (path, category, reason, public_interfaces, covered_by_tests)
ENTRIES: list[tuple[str, str, str, list[str], list[str]]] = [
    # --- FROZEN_CORE ---
    (
        "apps/api/app/db/models.py",
        "FROZEN_CORE",
        "ORM persistence for Book/Chapter/Paragraph/AnalysisRun/Scene/Artifact/Evidence/Journey",
        ["Book", "Chapter", "Paragraph", "AnalysisRun", "Scene", "AnalysisArtifact", "AnalysisEvidence", "ReaderJourneyRun", "SceneReaderJourneyProfile", "ReaderJourneyPhase", "ChapterReaderJourneySummary", "BoundaryRevision", "CloudBudgetReservation", "ModelInvocation"],
        ["apps/api/tests/test_migration.py", "apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "apps/api/app/db/session.py",
        "FROZEN_CORE",
        "DB bootstrap and incremental migrations; schema evolution entrypoint",
        ["create_db", "migrate_phase_1b", "migrate_phase_1c_c1", "SessionLocal", "get_db"],
        ["apps/api/tests/test_migration.py"],
    ),
    (
        "apps/api/app/domain/ingestion.py",
        "FROZEN_CORE",
        "Chapter detection rules and paragraph addressing foundation",
        ["detect_chapters", "ParsedChapter", "ChapterDetection"],
        ["apps/api/tests/test_import.py", "apps/api/tests/test_phase_2a1.py"],
    ),
    (
        "apps/api/app/services/extractors.py",
        "FROZEN_CORE",
        "TXT/DOCX/EPUB extraction into normalized text",
        ["extract_document", "ExtractedDocument"],
        ["apps/api/tests/test_import.py"],
    ),
    (
        "apps/api/app/services/book_service.py",
        "FROZEN_CORE",
        "Book import persistence and stable Book/Chapter/Paragraph IDs",
        ["import_book", "preview_book", "_write_chapters"],
        ["apps/api/tests/test_import.py"],
    ),
    (
        "apps/api/app/services/scene_pipeline.py",
        "FROZEN_CORE",
        "Scene boundary + analysis orchestration core",
        ["execute_scene_pipeline", "validate_scene_analysis", "classify_pipeline_error"],
        ["apps/api/tests/test_scene_pipeline.py", "apps/api/tests/test_phase_1c_a.py"],
    ),
    (
        "apps/api/app/services/boundary_review_service.py",
        "FROZEN_CORE",
        "Boundary review confirm → BoundaryRevision → Scene analysis",
        ["create_review_session", "confirm_review", "analyze_confirmed_review"],
        ["apps/api/tests/test_phase_1c_a8_review_confirm.py"],
    ),
    (
        "apps/api/app/services/boundary_detection_checkpoints.py",
        "FROZEN_CORE",
        "Detection batch checkpoints and offline recovery",
        ["upsert_detection_checkpoint", "recover_boundary_detection_from_invocations"],
        ["apps/api/tests/test_phase_1c_a7.py", "apps/api/tests/test_phase_1c_a10.py"],
    ),
    (
        "apps/api/app/services/scene_analysis_progress.py",
        "FROZEN_CORE",
        "Scene analysis progress, pending scenes, failure persistence",
        ["scene_analysis_progress", "pending_scenes_for_run", "persist_scene_analysis_failure"],
        ["apps/api/tests/test_phase_1c_a10.py"],
    ),
    (
        "apps/api/app/services/scene_analysis_offline_replay.py",
        "FROZEN_CORE",
        "Offline replay of scene analysis from stored invocations",
        ["offline_replay_scene_analysis"],
        ["apps/api/tests/test_phase_1c_a10.py"],
    ),
    (
        "apps/api/app/services/structured_output.py",
        "FROZEN_CORE",
        "Unified validated model generation + ModelInvocation persistence",
        ["generate_validated"],
        ["apps/api/tests/test_scene_pipeline.py", "apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "apps/api/app/services/prompt_service.py",
        "FROZEN_CORE",
        "Prompt loader from packages/prompts",
        ["load_prompt"],
        ["apps/api/tests/test_scene_pipeline.py"],
    ),
    (
        "apps/api/app/services/response_contract.py",
        "FROZEN_CORE",
        "Structured response contract helpers",
        [],
        [],
    ),
    (
        "apps/api/app/model_gateway/gateway.py",
        "FROZEN_CORE",
        "Unified ModelGateway protocol for local and cloud",
        ["ModelGateway", "generate"],
        ["apps/api/tests/test_model_gateway.py"],
    ),
    (
        "apps/api/app/model_gateway/registry.py",
        "FROZEN_CORE",
        "Provider registry assembly",
        ["get_model_gateway"],
        ["apps/api/tests/test_model_gateway.py"],
    ),
    (
        "apps/api/app/model_gateway/providers/openai_compatible.py",
        "FROZEN_CORE",
        "OpenAI-compatible HTTP provider (local + Aliyun)",
        ["OpenAICompatibleProvider"],
        ["apps/api/tests/test_aliyun_provider.py"],
    ),
    (
        "apps/api/app/services/provider_runtime_service.py",
        "FROZEN_CORE",
        "Canonical pre-send provider runtime resolution",
        ["ProviderRuntimeService.resolve_for_run"],
        ["apps/api/tests/test_phase_1c_a10.py"],
    ),
    (
        "apps/api/app/services/provider_runtime.py",
        "FROZEN_CORE",
        "DB overlay onto provider instances",
        [],
        ["apps/api/tests/test_phase_1c_a5.py"],
    ),
    (
        "apps/api/app/services/provider_eligibility.py",
        "FROZEN_CORE",
        "Manual/automatic route eligibility gates",
        [],
        ["apps/api/tests/test_phase_1c_a.py"],
    ),
    (
        "apps/api/app/services/budget_reservation.py",
        "FROZEN_CORE",
        "Cloud budget reservation and release",
        ["reserve_budget", "release_run_reservation", "InsufficientBudgetReservation"],
        ["apps/api/tests/test_phase_1c_a4.py", "apps/api/tests/test_cloud_budget.py"],
    ),
    (
        "apps/api/app/services/staged_budget.py",
        "FROZEN_CORE",
        "Staged budget estimates for boundary/analysis/journey",
        ["STAGE_BOUNDARY", "STAGE_ANALYSIS", "estimate_stage1_boundary", "estimate_stage2_scene_analysis"],
        ["apps/api/tests/test_phase_1c_a4.py"],
    ),
    (
        "apps/api/app/services/cloud_budget.py",
        "FROZEN_CORE",
        "Daily cloud usage aggregation",
        ["daily_usage"],
        ["apps/api/tests/test_cloud_budget.py"],
    ),
    (
        "apps/api/app/services/cloud_pricing.py",
        "FROZEN_CORE",
        "Cloud pricing estimates from config",
        ["pricing_status", "estimate_cost"],
        ["apps/api/tests/test_cloud_budget.py"],
    ),
    (
        "apps/api/app/services/cloud_output_policy.py",
        "FROZEN_CORE",
        "Output token caps per task type",
        [],
        [],
    ),
    (
        "apps/api/app/services/scene_transitions.py",
        "FROZEN_CORE",
        "Adjacent transition building for boundary detection",
        ["build_adjacent_transitions", "validate_and_map_transitions"],
        ["apps/api/tests/test_phase_2b1.py"],
    ),
    (
        "apps/api/app/services/transition_batch_planner.py",
        "FROZEN_CORE",
        "Transition batch planning for v3.x boundary",
        ["plan_transition_batches"],
        ["apps/api/tests/test_phase_2b2.py"],
    ),
    (
        "apps/api/app/services/scene_boundary_adjudicator.py",
        "FROZEN_CORE",
        "v3.5 adjudication to canonical boundaries",
        ["plan_adjudication_batches", "adjudicated_to_canonical"],
        ["apps/api/tests/test_phase_2b8.py"],
    ),
    (
        "apps/api/app/services/compact_transition_adapter.py",
        "FROZEN_CORE",
        "Compact transition → canonical adapter",
        ["compact_to_canonical"],
        ["apps/api/tests/test_phase_2b3.py"],
    ),
    (
        "apps/api/app/services/compact_transition_adapter_v34.py",
        "FROZEN_CORE",
        "v3.4 compact transition adapter",
        ["compact_v34_to_canonical"],
        ["apps/api/tests/test_phase_2b4.py"],
    ),
    (
        "apps/api/app/services/reader_journey_pipeline.py",
        "FROZEN_CORE",
        "Reader journey execution: profiles → synthesis → persistence",
        ["execute_reader_journey", "build_preflight_payload"],
        ["apps/api/tests/test_phase_1c_c1.py", "apps/api/tests/test_phase_1c_c1_2.py"],
    ),
    (
        "apps/api/app/services/reader_journey_validation.py",
        "FROZEN_CORE",
        "Journey business validation and evidence scope checks",
        ["validate_scene_batch_result", "validate_chapter_synthesis"],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "apps/api/app/services/reader_journey_semantic_calibrate.py",
        "FROZEN_CORE",
        "Offline semantic calibration (q_in chain, hooks, journey_nodes)",
        ["semantic_recalibrate_journey_run", "apply_deterministic_qin"],
        ["apps/api/tests/test_phase_1c_c1_5.py"],
    ),
    (
        "apps/api/app/services/reader_journey_visualization.py",
        "FROZEN_CORE",
        "Deterministic visualization aggregate (zero model)",
        ["build_reader_journey_visualization"],
        ["apps/api/tests/test_phase_1c_c2.py", "apps/api/tests/test_phase_1c_c2_1.py"],
    ),
    (
        "apps/api/app/services/reader_journey_visual_calibration.py",
        "FROZEN_CORE",
        "Visualization 1.1 formulas: levels, hooks, payoffs, clusters",
        ["VISUALIZATION_VERSION", "classify_scene_levels", "select_visible_hooks", "derive_and_select_payoffs", "build_question_clusters"],
        ["apps/api/tests/test_phase_1c_c2_1.py"],
    ),
    (
        "apps/api/app/services/reader_journey_engagement.py",
        "FROZEN_CORE",
        "Engagement formula from config/reader_journey_formulas.json",
        ["compute_engagement", "load_formula_config"],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "apps/api/app/services/reader_journey_batch_planner.py",
        "FROZEN_CORE",
        "Scene profile batch planner",
        ["plan_scene_batches", "PLANNER_VERSION"],
        ["apps/api/tests/test_phase_1c_c1_2.py"],
    ),
    (
        "apps/api/app/services/reader_journey_offline_replay.py",
        "FROZEN_CORE",
        "Offline replay of journey profiles from invocations",
        ["offline_replay_journey_profiles"],
        ["apps/api/tests/test_phase_1c_c1_3.py"],
    ),
    (
        "apps/api/app/services/reader_journey_progress.py",
        "FROZEN_CORE",
        "Journey progress and recoverable-run discovery",
        ["reader_journey_progress", "find_recoverable_journey_run"],
        ["apps/api/tests/test_phase_1c_c1_4.py"],
    ),
    (
        "apps/api/app/services/reader_journey_statistics.py",
        "FROZEN_CORE",
        "Deterministic chapter journey statistics",
        [],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "apps/api/app/services/reader_journey_question_lifecycle.py",
        "FROZEN_CORE",
        "Question lifecycle helpers for chains",
        [],
        ["apps/api/tests/test_phase_1c_c2.py"],
    ),
    (
        "apps/api/app/services/reader_journey_contract_migrate.py",
        "FROZEN_CORE",
        "Contract migration for offline profile upgrades",
        [],
        ["apps/api/tests/test_phase_1c_c1_3.py"],
    ),
    (
        "apps/api/app/services/scene_results_service.py",
        "FROZEN_CORE",
        "Run results bundle assembly (scenes + artifacts + evidence)",
        ["build_run_results", "build_scene_bundle"],
        ["apps/api/tests/test_phase_1c_b_results.py"],
    ),
    (
        "apps/api/app/services/scene_results_export.py",
        "FROZEN_CORE",
        "Markdown/JSON export rendering for scene analysis",
        ["render_markdown"],
        ["apps/api/tests/test_phase_1c_b_results.py"],
    ),
    (
        "config/reader_journey_formulas.json",
        "FROZEN_CORE",
        "Engagement formula weights version 1.0",
        ["version", "genres"],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "config/cloud_pricing.json",
        "FROZEN_CORE",
        "Cloud pricing table used by budget estimates",
        [],
        ["apps/api/tests/test_cloud_budget.py"],
    ),
    # Active prompts (freeze active versions)
    (
        "packages/prompts/scene_boundary/v3.5/system.md",
        "FROZEN_CORE",
        "Active cloud boundary system prompt v3.5",
        [],
        ["apps/api/tests/test_phase_1c_a.py"],
    ),
    (
        "packages/prompts/scene_boundary/v3.5/user.md",
        "FROZEN_CORE",
        "Active cloud boundary user prompt v3.5",
        [],
        [],
    ),
    (
        "packages/prompts/scene_boundary/v3.5/repair.md",
        "FROZEN_CORE",
        "Active cloud boundary repair prompt v3.5",
        [],
        [],
    ),
    (
        "packages/prompts/scene_boundary_adjudication/v1/system.md",
        "FROZEN_CORE",
        "Boundary adjudication system prompt",
        [],
        [],
    ),
    (
        "packages/prompts/scene_boundary_adjudication/v1/user.md",
        "FROZEN_CORE",
        "Boundary adjudication user prompt",
        [],
        [],
    ),
    (
        "packages/prompts/scene_boundary_adjudication/v1/repair.md",
        "FROZEN_CORE",
        "Boundary adjudication repair prompt",
        [],
        [],
    ),
    (
        "packages/prompts/scene_analysis/v3.1/system.md",
        "FROZEN_CORE",
        "Active scene analysis system prompt v3.1",
        [],
        ["apps/api/tests/test_phase_1c_a10.py"],
    ),
    (
        "packages/prompts/scene_analysis/v3.1/user.md",
        "FROZEN_CORE",
        "Active scene analysis user prompt v3.1",
        [],
        [],
    ),
    (
        "packages/prompts/scene_analysis/v3.1/repair.md",
        "FROZEN_CORE",
        "Active scene analysis repair prompt v3.1",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.3/system.md",
        "FROZEN_CORE",
        "Historical reader journey scene system prompt v1.3 (superseded by v1.4)",
        [],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.3/user.md",
        "FROZEN_CORE",
        "Historical reader journey scene user prompt v1.3 (superseded by v1.4)",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.3/repair.md",
        "FROZEN_CORE",
        "Historical reader journey scene repair prompt v1.3 (superseded by v1.4)",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.4/system.md",
        "FROZEN_CORE",
        "Active reader journey scene system prompt v1.4",
        [],
        ["apps/api/tests/test_defect_canary_006_question_lifecycle.py"],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.4/user.md",
        "FROZEN_CORE",
        "Active reader journey scene user prompt v1.4",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_scene/v1.4/repair.md",
        "FROZEN_CORE",
        "Active reader journey scene repair prompt v1.4",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_chapter/v1.1/system.md",
        "FROZEN_CORE",
        "Active chapter synthesis system prompt v1.1 (code default; JourneyRun#2 stored v1)",
        [],
        ["apps/api/tests/test_phase_1c_c1.py"],
    ),
    (
        "packages/prompts/reader_journey_chapter/v1.1/user.md",
        "FROZEN_CORE",
        "Active chapter synthesis user prompt v1.1",
        [],
        [],
    ),
    (
        "packages/prompts/reader_journey_chapter/v1.1/repair.md",
        "FROZEN_CORE",
        "Active chapter synthesis repair prompt v1.1",
        [],
        [],
    ),
    # --- FROZEN_CONTRACT ---
    (
        "apps/api/app/schemas/scene.py",
        "FROZEN_CONTRACT",
        "Pydantic contracts for scene boundary/analysis runs and results",
        ["SceneAnalysisResult", "SceneBoundaryResult", "AnalysisRunCreate", "RunResultsBundle"],
        ["apps/api/tests/test_phase_1c_b_results.py"],
    ),
    (
        "apps/api/app/schemas/reader_journey.py",
        "FROZEN_CONTRACT",
        "Pydantic contracts and version pins for reader journey",
        ["SCENE_PROMPT_VERSION", "SCENE_CONTRACT_VERSION", "SceneReaderJourneyProfileItem", "ChapterReaderJourneySynthesisResult"],
        ["apps/api/tests/test_phase_1c_c1.py", "apps/api/tests/test_phase_1c_c2.py"],
    ),
    (
        "apps/api/app/schemas/boundary_review.py",
        "FROZEN_CONTRACT",
        "Boundary review API/DTO contracts",
        [],
        ["apps/api/tests/test_phase_1c_a8_review_confirm.py"],
    ),
    (
        "apps/api/app/schemas/book.py",
        "FROZEN_CONTRACT",
        "Book/Chapter/Paragraph API DTOs",
        ["ImportResponse", "BookResponse", "ChapterResponse", "ParagraphPage"],
        ["apps/api/tests/test_import.py"],
    ),
    (
        "apps/api/app/api/v1/analysis.py",
        "FROZEN_CONTRACT",
        "Analysis run/resume/results API surface (semantics frozen)",
        ["create_analysis_run", "get_analysis_run", "resume_scene_analysis"],
        ["apps/api/tests/test_phase_1c_a10.py", "apps/api/tests/test_phase_1c_b_results.py"],
    ),
    (
        "apps/api/app/api/v1/boundary_reviews.py",
        "FROZEN_CONTRACT",
        "Boundary review API surface",
        ["confirm_boundary_review"],
        ["apps/api/tests/test_phase_1c_a8_review_confirm.py"],
    ),
    (
        "apps/api/app/api/v1/reader_journey.py",
        "FROZEN_CONTRACT",
        "Reader journey API surface including visualization payload",
        ["create_reader_journey", "_serialize_result", "semantic_recalibrate"],
        ["apps/api/tests/test_phase_1c_c1.py", "apps/api/tests/test_phase_1c_c2.py"],
    ),
    (
        "apps/api/app/api/v1/router.py",
        "FROZEN_CONTRACT",
        "Books import/chapters/paragraphs API surface",
        ["upload_book", "list_chapters", "list_paragraphs"],
        ["apps/api/tests/test_import.py"],
    ),
    (
        "apps/desktop/src/types/index.ts",
        "FROZEN_CONTRACT",
        "TypeScript mirrors of core API entities and run results",
        ["RunResults", "SceneResultItem", "ReaderJourneyResult", "Run"],
        ["apps/desktop/src/pages/AnalysisResultsPage.test.tsx"],
    ),
    (
        "apps/desktop/src/types/readerJourneyVisualization.ts",
        "FROZEN_CONTRACT",
        "TypeScript visualization 1.1 contract",
        ["ReaderJourneyVisualization", "JourneySceneNode", "JourneyCurveMetric"],
        ["apps/desktop/src/components/readerJourney/ReaderJourneyWorkspace.test.tsx"],
    ),
    (
        "apps/desktop/src/types/journeySelection.ts",
        "FROZEN_CONTRACT",
        "Journey selection state and URL param contract",
        ["JourneySelectionState", "JourneyPageMode", "JourneySelectionPatch"],
        ["apps/desktop/e2e/phase_1cc2_2_sync_workspace.spec.ts"],
    ),
    (
        "apps/desktop/src/types/readerJourneyProfileItems.ts",
        "FROZEN_CONTRACT",
        "Normalized profile item shapes (contract 1.3)",
        [],
        ["apps/desktop/src/components/readerJourney/sceneDetailFields.test.tsx"],
    ),
    (
        "apps/desktop/src/services/analysisApi.ts",
        "FROZEN_CONTRACT",
        "Desktop analysis/journey API client methods and paths",
        ["analysisApi"],
        ["apps/desktop/src/pages/AnalysisResultsPage.test.tsx"],
    ),
    (
        "apps/desktop/src/services/apiClient.ts",
        "FROZEN_CONTRACT",
        "HTTP client and ApiError mapping",
        ["api", "ApiError"],
        [],
    ),
    (
        "apps/desktop/src/services/booksApi.ts",
        "FROZEN_CONTRACT",
        "Books import/list/chapter API client",
        ["booksApi"],
        [],
    ),
    # --- REUSABLE_UI_LOGIC ---
    (
        "apps/desktop/src/hooks/useJourneySelection.ts",
        "REUSABLE_UI_LOGIC",
        "URL↔selection state machine; must not be reimplemented",
        ["useJourneySelection"],
        ["apps/desktop/e2e/phase_1cc2_2_sync_workspace.spec.ts"],
    ),
    (
        "apps/desktop/src/components/readerJourney/ReaderJourneySyncWorkspace.tsx",
        "REUSABLE_UI_LOGIC",
        "Text–journey sync orchestration",
        ["ReaderJourneySyncWorkspace"],
        ["apps/desktop/src/components/readerJourney/ReaderJourneySyncWorkspace.test.tsx", "apps/desktop/e2e/phase_1cc2_2_sync_workspace.spec.ts"],
    ),
    (
        "apps/desktop/src/components/readerJourney/ReaderJourneyWorkspace.tsx",
        "REUSABLE_UI_LOGIC",
        "Curve/phases/clusters/detail drawer controlled selection",
        ["ReaderJourneyWorkspace"],
        ["apps/desktop/src/components/readerJourney/ReaderJourneyWorkspace.test.tsx"],
    ),
    (
        "apps/desktop/src/components/readerJourney/StructuredChapterTextPane.tsx",
        "REUSABLE_UI_LOGIC",
        "Structured chapter text + scroll spy + evidence marks",
        ["StructuredChapterTextPane"],
        ["apps/desktop/src/components/readerJourney/StructuredChapterTextPane.test.tsx"],
    ),
    (
        "apps/desktop/src/components/readerJourney/sceneDetailFields.tsx",
        "REUSABLE_UI_LOGIC",
        "Structured scene detail field renderers with evidence locate",
        ["WritingTakeawayList", "HookList", "PayoffList"],
        ["apps/desktop/src/components/readerJourney/sceneDetailFields.test.tsx"],
    ),
    (
        "apps/desktop/src/components/readerJourney/safeRender.ts",
        "REUSABLE_UI_LOGIC",
        "Defensive normalization so unknown objects never crash React",
        ["normalizeTechnique", "normalizeHook", "renderFallbackValue"],
        ["apps/desktop/src/components/readerJourney/sceneDetailFields.test.tsx"],
    ),
    (
        "apps/desktop/src/components/readerJourney/JourneyDetailErrorBoundary.tsx",
        "REUSABLE_UI_LOGIC",
        "Isolates scene detail render failures",
        ["JourneyDetailErrorBoundary"],
        ["apps/desktop/src/components/readerJourney/sceneDetailFields.test.tsx"],
    ),
    (
        "apps/desktop/src/components/readerJourney/exportJourneyPng.ts",
        "REUSABLE_UI_LOGIC",
        "PNG export from journey-export-root",
        ["exportJourneyPng"],
        ["apps/desktop/e2e/phase_1cc2_reader_journey_visual.spec.ts"],
    ),
    (
        "apps/desktop/src/components/readerJourney/exportSceneCard.ts",
        "REUSABLE_UI_LOGIC",
        "Scene card PNG/Markdown export",
        ["exportSceneCardPng", "exportSceneCardMarkdown"],
        [],
    ),
    (
        "apps/desktop/src/components/readerJourney/SplitPane.tsx",
        "REUSABLE_UI_LOGIC",
        "Split ratio persistence and responsive split behavior",
        ["SplitPane"],
        ["apps/desktop/e2e/phase_1cc2_2_sync_workspace.spec.ts"],
    ),
    (
        "apps/desktop/src/pages/AnalysisResultsPage.tsx",
        "REUSABLE_UI_LOGIC",
        "Results + journey lifecycle gating (logic portions reusable)",
        ["AnalysisResultsPage"],
        ["apps/desktop/src/pages/AnalysisResultsPage.test.tsx", "apps/desktop/e2e/phase_1cb_results.spec.ts"],
    ),
    (
        "apps/desktop/src/pages/TasksPage.tsx",
        "REUSABLE_UI_LOGIC",
        "Task center recovery/resume state machines",
        ["TasksPage"],
        ["apps/desktop/src/pages/TasksPage.test.tsx", "apps/desktop/e2e/phase_1ca10_scene_resume.spec.ts"],
    ),
    (
        "apps/desktop/src/pages/BookWorkspacePage.tsx",
        "REUSABLE_UI_LOGIC",
        "Chapter reading + analysis start + evidence locate",
        ["BookWorkspacePage"],
        [],
    ),
    (
        "apps/desktop/src/components/analysis/StartAnalysisDialog.tsx",
        "REUSABLE_UI_LOGIC",
        "Analysis creation + cloud consent + staged budget preflight UI",
        ["StartAnalysisDialog"],
        ["apps/desktop/src/components/analysis/StartAnalysisDialog.test.tsx"],
    ),
    (
        "apps/desktop/src/components/analysis/BoundaryReviewPanel.tsx",
        "REUSABLE_UI_LOGIC",
        "Boundary review decisions and confirm gating",
        ["BoundaryReviewPanel"],
        ["apps/desktop/src/components/analysis/BoundaryReviewPanel.test.tsx", "apps/desktop/e2e/phase_1ca8_boundary_review.spec.ts"],
    ),
]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> None:
    files = []
    missing = []
    for rel, category, reason, interfaces, tests in ENTRIES:
        path = ROOT / rel.replace("/", "\\") if False else ROOT / Path(*rel.split("/"))
        if not path.exists():
            missing.append(rel)
            continue
        files.append(
            {
                "path": rel,
                "category": category,
                "sha256": sha256_file(path),
                "reason": reason,
                "public_interfaces": interfaces,
                "covered_by_tests": tests,
            }
        )

    counts = {
        "FROZEN_CORE": sum(1 for f in files if f["category"] == "FROZEN_CORE"),
        "FROZEN_CONTRACT": sum(1 for f in files if f["category"] == "FROZEN_CONTRACT"),
        "REUSABLE_UI_LOGIC": sum(1 for f in files if f["category"] == "REUSABLE_UI_LOGIC"),
    }

    # UI shell changeable (documented, not hashed as freeze gate)
    ui_shell = [
        "apps/desktop/src/app/router.tsx",
        "apps/desktop/src/app/App.tsx",
        "apps/desktop/src/components/layout/AppShell.tsx",
        "apps/desktop/src/pages/HomePage.tsx",
        "apps/desktop/src/pages/LibraryPage.tsx",
        "apps/desktop/src/pages/WorkspaceLandingPage.tsx",
        "apps/desktop/src/pages/CasesPage.tsx",
        "apps/desktop/src/pages/ProvidersPage.tsx",
        "apps/desktop/src/pages/SettingsPage.tsx",
        "apps/desktop/src/pages/BookRoutePage.tsx",
        "apps/desktop/src/components/common/States.tsx",
        "apps/desktop/src/components/readerJourney/SceneStructureDrawer.tsx",
        "apps/desktop/src/components/readerJourney/journeyVisualTokens.ts",
        "apps/desktop/src/components/readerJourney/readerJourney.css",
        "apps/desktop/src/components/readerJourney/syncWorkspace.css",
        "apps/desktop/src/styles/global.css",
    ]

    manifest = {
        "baseline_name": "mvp-functional-baseline-v1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "git_commit": None,
        "git_worktree_status": "not_a_git_repository",
        "database_path": "data/storylens.db",
        "schema_version": {
            "migrations": [
                "migrate_phase_1b",
                "migrate_phase_2a1",
                "migrate_phase_2b1",
                "migrate_phase_2b2",
                "migrate_phase_1c_a",
                "migrate_phase_1c_a3",
                "migrate_phase_1c_a4",
                "migrate_phase_1c_a7",
                "migrate_phase_1c_c1",
            ],
            "note": "No single schema_version table; migrations are idempotent functions in session.py",
        },
        "prompt_versions": {
            "scene_boundary_cloud": "v3.5",
            "scene_boundary_adjudication": "v1",
            "scene_analysis": "v3.1",
            "reader_journey_scene": "v1.4",
            "reader_journey_chapter_code_default": "v1.1",
            "reader_journey_chapter_journey_run_2_stored": "v1",
        },
        "formula_versions": {
            "engagement": "1.0",
            "importance": "1.1",
            "hook_select": "1.1",
            "payoff_derive": "1.1",
            "cluster": "1.1",
            "chain_rank": "1.0",
            "chain_merge": "1.0",
        },
        "visualization_version": "1.1",
        "contract_versions": {
            "scene_contract": "1.3",
            "chapter_contract_code_default": "1.1",
            "chapter_contract_journey_run_2_stored": "1.0",
            "planner_version": "1.1",
        },
        "test_counts": {
            "pytest_passed": 271,
            "vitest_passed": 111,
            "e2e_passed": 19,
            "ruff": "passed",
            "typescript": "passed",
            "eslint": "passed",
            "build": "passed",
        },
        "category_counts": counts,
        "ui_shell_changeable_count": len(ui_shell),
        "ui_shell_changeable": ui_shell,
        "missing_files": missing,
        "files": files,
        "golden_sample": {
            "analysis_run_id": 55,
            "boundary_revision_id": 1,
            "reader_journey_run_id": 2,
            "scene_ids": list(range(6, 20)),
        },
        "constraints": {
            "real_model_requests": 0,
            "tokens": 0,
            "cost": 0,
            "no_production_code_modified": True,
            "phase_1c_c2_3_not_executed": True,
        },
    }
    OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"counts={counts} shell={len(ui_shell)} missing={missing}")


if __name__ == "__main__":
    main()
