"""Whole-book cost estimate + consent error codes (WB-0.3)."""

from __future__ import annotations

from enum import StrEnum


class WholeBookFoundationErrorCode(StrEnum):
    WHOLE_BOOK_ESTIMATE_EXPIRED = "WHOLE_BOOK_ESTIMATE_EXPIRED"
    WHOLE_BOOK_BOOK_CHANGED = "WHOLE_BOOK_BOOK_CHANGED"
    WHOLE_BOOK_PRICING_UNAVAILABLE = "WHOLE_BOOK_PRICING_UNAVAILABLE"
    WHOLE_BOOK_BUDGET_TOO_LOW = "WHOLE_BOOK_BUDGET_TOO_LOW"
    WHOLE_BOOK_CALL_LIMIT_REQUIRED = "WHOLE_BOOK_CALL_LIMIT_REQUIRED"
    WHOLE_BOOK_TOKEN_LIMIT_REQUIRED = "WHOLE_BOOK_TOKEN_LIMIT_REQUIRED"
    WHOLE_BOOK_CONSENT_REVOKED = "WHOLE_BOOK_CONSENT_REVOKED"
    WHOLE_BOOK_CAPABILITY_DISABLED = "WHOLE_BOOK_CAPABILITY_DISABLED"
    WHOLE_BOOK_CONSENT_REQUIRED = "WHOLE_BOOK_CONSENT_REQUIRED"
    WHOLE_BOOK_CONSENT_EXPIRED = "WHOLE_BOOK_CONSENT_EXPIRED"
    WHOLE_BOOK_CALL_BUDGET_EXCEEDED = "WHOLE_BOOK_CALL_BUDGET_EXCEEDED"
    WHOLE_BOOK_INPUT_TOKEN_BUDGET_EXCEEDED = "WHOLE_BOOK_INPUT_TOKEN_BUDGET_EXCEEDED"
    WHOLE_BOOK_OUTPUT_TOKEN_BUDGET_EXCEEDED = "WHOLE_BOOK_OUTPUT_TOKEN_BUDGET_EXCEEDED"
    WHOLE_BOOK_COST_BUDGET_EXCEEDED = "WHOLE_BOOK_COST_BUDGET_EXCEEDED"
    WHOLE_BOOK_UNIT_RUNNING = "WHOLE_BOOK_UNIT_RUNNING"
    WHOLE_BOOK_RETRY_NOT_ALLOWED = "WHOLE_BOOK_RETRY_NOT_ALLOWED"
    WHOLE_BOOK_RETRY_LIMIT_EXCEEDED = "WHOLE_BOOK_RETRY_LIMIT_EXCEEDED"
    WHOLE_BOOK_SNAPSHOT_NOT_FOUND = "WHOLE_BOOK_SNAPSHOT_NOT_FOUND"
    WHOLE_BOOK_SNAPSHOT_BOOK_MISMATCH = "WHOLE_BOOK_SNAPSHOT_BOOK_MISMATCH"
    WHOLE_BOOK_SNAPSHOT_NOT_COMPLETED = "WHOLE_BOOK_SNAPSHOT_NOT_COMPLETED"
    WHOLE_BOOK_RUN_INVALID_TRANSITION = "WHOLE_BOOK_RUN_INVALID_TRANSITION"
    WHOLE_BOOK_RUN_TERMINAL = "WHOLE_BOOK_RUN_TERMINAL"
    WHOLE_BOOK_RUN_NOT_FOUND = "WHOLE_BOOK_RUN_NOT_FOUND"
    WHOLE_BOOK_CLIENT_REQUEST_CONFLICT = "WHOLE_BOOK_CLIENT_REQUEST_CONFLICT"
    WHOLE_BOOK_WINDOW_SET_CONFLICT = "WHOLE_BOOK_WINDOW_SET_CONFLICT"
    UPDATE_COMPLETED_FORBIDDEN = "update_completed_forbidden"


class WholeBookFoundationError(Exception):
    def __init__(self, code: WholeBookFoundationErrorCode | str, message: str) -> None:
        self.code = code.value if isinstance(code, WholeBookFoundationErrorCode) else str(code)
        self.message = message
        super().__init__(message)
