"""Whole-book cost estimate + consent error codes (WB-0.3)."""

from __future__ import annotations

from enum import StrEnum


class WholeBookFoundationErrorCode(StrEnum):
    WHOLE_BOOK_ESTIMATE_EXPIRED = "WHOLE_BOOK_ESTIMATE_EXPIRED"
    WHOLE_BOOK_BOOK_CHANGED = "WHOLE_BOOK_BOOK_CHANGED"
    WHOLE_BOOK_BOOK_NOT_FOUND = "WHOLE_BOOK_BOOK_NOT_FOUND"
    WHOLE_BOOK_PRICING_UNAVAILABLE = "WHOLE_BOOK_PRICING_UNAVAILABLE"
    WHOLE_BOOK_BUDGET_TOO_LOW = "WHOLE_BOOK_BUDGET_TOO_LOW"
    BUDGET_TOO_LOW = "BUDGET_TOO_LOW"
    LIMIT_PROVIDER_CALLS_TOO_LOW = "LIMIT_PROVIDER_CALLS_TOO_LOW"
    LIMIT_INPUT_TOKENS_TOO_LOW = "LIMIT_INPUT_TOKENS_TOO_LOW"
    LIMIT_OUTPUT_TOKENS_TOO_LOW = "LIMIT_OUTPUT_TOKENS_TOO_LOW"
    CONSENT_STALE = "CONSENT_STALE"
    REQUEST_SCHEMA_INVALID = "REQUEST_SCHEMA_INVALID"
    WHOLE_BOOK_CALL_LIMIT_REQUIRED = "WHOLE_BOOK_CALL_LIMIT_REQUIRED"
    WHOLE_BOOK_TOKEN_LIMIT_REQUIRED = "WHOLE_BOOK_TOKEN_LIMIT_REQUIRED"
    WHOLE_BOOK_CONSENT_REVOKED = "WHOLE_BOOK_CONSENT_REVOKED"
    WHOLE_BOOK_CAPABILITY_DISABLED = "WHOLE_BOOK_CAPABILITY_DISABLED"
    WHOLE_BOOK_CONSENT_REQUIRED = "WHOLE_BOOK_CONSENT_REQUIRED"
    WHOLE_BOOK_CONSENT_EXPIRED = "WHOLE_BOOK_CONSENT_EXPIRED"
    WHOLE_BOOK_CALL_BUDGET_EXCEEDED = "WHOLE_BOOK_CALL_BUDGET_EXCEEDED"
    WHOLE_BOOK_INPUT_TOKEN_BUDGET_EXCEEDED = "WHOLE_BOOK_INPUT_TOKEN_BUDGET_EXCEEDED"
    WHOLE_BOOK_OUTPUT_TOKEN_BUDGET_EXCEEDED = "WHOLE_BOOK_OUTPUT_TOKEN_BUDGET_EXCEEDED"
    WHOLE_BOOK_COST_BUDGET_EXCEEDED = "WHOLE_BOOK_COST_BUDGET_EXCEEDED"
    WHOLE_BOOK_UNIT_RUNNING = "WHOLE_BOOK_UNIT_RUNNING"
    WHOLE_BOOK_RETRY_NOT_ALLOWED = "WHOLE_BOOK_RETRY_NOT_ALLOWED"
    WHOLE_BOOK_RETRY_LIMIT_EXCEEDED = "WHOLE_BOOK_RETRY_LIMIT_EXCEEDED"
    WHOLE_BOOK_SNAPSHOT_NOT_FOUND = "WHOLE_BOOK_SNAPSHOT_NOT_FOUND"
    WHOLE_BOOK_SNAPSHOT_BOOK_MISMATCH = "WHOLE_BOOK_SNAPSHOT_BOOK_MISMATCH"
    WHOLE_BOOK_SNAPSHOT_NOT_COMPLETED = "WHOLE_BOOK_SNAPSHOT_NOT_COMPLETED"
    WHOLE_BOOK_RUN_INVALID_TRANSITION = "WHOLE_BOOK_RUN_INVALID_TRANSITION"
    WHOLE_BOOK_RUN_TERMINAL = "WHOLE_BOOK_RUN_TERMINAL"
    WHOLE_BOOK_RUN_NOT_FOUND = "WHOLE_BOOK_RUN_NOT_FOUND"
    #: The requested reading of the book is not available for this book — 拆文 lives in the
    #: long-novel engine, and a book that engine will not take can only be read diagnostically.
    WHOLE_BOOK_MODE_UNAVAILABLE = "WHOLE_BOOK_MODE_UNAVAILABLE"
    WHOLE_BOOK_CLIENT_REQUEST_CONFLICT = "WHOLE_BOOK_CLIENT_REQUEST_CONFLICT"
    WHOLE_BOOK_WINDOW_SET_CONFLICT = "WHOLE_BOOK_WINDOW_SET_CONFLICT"
    UPDATE_COMPLETED_FORBIDDEN = "update_completed_forbidden"
    WHOLE_BOOK_REAL_PROVIDER_DISABLED = "WHOLE_BOOK_REAL_PROVIDER_DISABLED"
    WHOLE_BOOK_FREE_PRODUCT_DISABLED = "WHOLE_BOOK_FREE_PRODUCT_DISABLED"
    WHOLE_BOOK_NATIVE_INPUT_CONTAMINATED = "WHOLE_BOOK_NATIVE_INPUT_CONTAMINATED"
    WHOLE_BOOK_FIXTURE_PREVIEW_DISABLED = "WHOLE_BOOK_FIXTURE_PREVIEW_DISABLED"
    #: A single chapter is larger than one window can hold, so the book cannot be planned at
    #: all. Almost always a chapter-splitting failure rather than a genuinely huge chapter:
    #: 《穿越之种田难为》 arrived as 2 chapters holding 390,000 characters. It needs its own
    #: code because the planner raised a bare ValueError, which surfaced as a 500 and was
    #: reported to the reader as 「本地分析服务暂时不可用」 — sending them to restart a service
    #: that was never down, instead of to the file that was never split.
    WHOLE_BOOK_CHAPTER_TOO_LARGE = "WHOLE_BOOK_CHAPTER_TOO_LARGE"


class WholeBookFoundationError(Exception):
    def __init__(
        self,
        code: WholeBookFoundationErrorCode | str,
        message: str,
        *,
        details: dict | None = None,
    ) -> None:
        self.code = code.value if isinstance(code, WholeBookFoundationErrorCode) else str(code)
        self.message = message
        self.details = details or {}
        super().__init__(message)
