export type SavedFileResult = {
  filename: string;
  path?: string;
};

function isTauriDesktop(): boolean {
  return typeof window !== "undefined" && "__TAURI_INTERNALS__" in window;
}

async function blobBytes(blob: Blob): Promise<number[]> {
  if (typeof blob.arrayBuffer === "function") {
    return Array.from(new Uint8Array(await blob.arrayBuffer()));
  }
  const buffer = await new Promise<ArrayBuffer>((resolve, reject) => {
    const reader = new FileReader();
    reader.onerror = () => reject(reader.error ?? new Error("读取导出文件失败。"));
    reader.onload = () => resolve(reader.result as ArrayBuffer);
    reader.readAsArrayBuffer(blob);
  });
  return Array.from(new Uint8Array(buffer));
}

/**
 * Save generated bytes reliably in both the installed desktop app and browser development.
 * Tauri's WebView can silently ignore `<a download>`, so desktop builds delegate the final write
 * to Rust and return the exact system Downloads path for user confirmation.
 */
export async function saveBlobAsFile(blob: Blob, filename: string): Promise<SavedFileResult> {
  if (isTauriDesktop()) {
    const { invoke } = await import("@tauri-apps/api/core");
    const path = await invoke<string>("save_download_file", {
      filename,
      bytes: await blobBytes(blob),
    });
    return { filename, path };
  }

  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
  return { filename };
}

export function savedFileMessage(result: SavedFileResult): string {
  return result.path ? `已保存到：${result.path}` : `已开始下载：${result.filename}`;
}
