export type Book = {
  id: number;
  title: string;
  author?: string;
  source_file_name: string;
  source_file_hash: string;
  created_at: string;
  revision_of_book_id?: number;
  revision_number: number;
};
export type Chapter = {
  id: number;
  book_id: number;
  chapter_index: number;
  title: string;
  word_count: number;
  section_type: string;
  display_title: string;
  chapter_number_normalized?: number;
};
export type Paragraph = {
  id: string;
  chapter_id: number;
  paragraph_index: number;
  raw_text: string;
};
export type ParagraphPage = {
  items: Paragraph[];
  offset: number;
  limit: number;
  total: number;
  has_more: boolean;
};
export type ImportDiagnostics = {
  encoding: string;
  byte_count: number;
  candidate_count: number;
  final_chapter_count: number;
  chapter_titles: string[];
  warning?: string;
  recommended_to_import: boolean;
  max_chapter_characters: number;
  max_chapter_paragraphs: number;
  old_chapter_count?: number;
};
export type Scene = {
  id: number;
  scene_key: string;
  chapter_id: number;
  ordinal: number;
  start_paragraph_id: string;
  end_paragraph_id: string;
  created_by_run_id: number;
  boundary_detected: boolean;
  boundary_confidence: number;
};
export type SceneEvidenceItem = {
  field_path: string;
  group: string;
  paragraph_id: string;
  in_scope: boolean;
  order_index: number;
};
export type SceneAnalysisFields = {
  scene_id?: string;
  entry_state?: { summary: string; evidence_paragraph_ids: string[] };
  goal?: { summary: string; evidence_paragraph_ids: string[] };
  obstacle?: { summary: string; evidence_paragraph_ids: string[] };
  key_actions?: { summary: string; evidence_paragraph_ids: string[] }[];
  turning_point?: { summary: string; evidence_paragraph_ids: string[] };
  outcome?: { summary: string; evidence_paragraph_ids: string[] };
  unresolved_question?: { summary: string; evidence_paragraph_ids: string[] };
  function_tags?: string[];
  confidence?: number;
};
export type SceneResultArtifact = {
  id: number;
  schema_version: string;
  prompt_version: string;
  provider: string;
  model: string;
  confidence: number;
  validation_status: string;
  created_at?: string;
  offline_recovered: boolean;
  analysis: SceneAnalysisFields;
};
export type SceneResultScene = {
  id: number;
  scene_key: string;
  ordinal: number;
  start_paragraph_id: string;
  end_paragraph_id: string;
  paragraph_count: number;
  is_single_paragraph: boolean;
  boundary_source?: string | null;
  boundary_revision_id?: number | null;
  boundary_detected: boolean;
  boundary_confidence: number;
};
export type SceneResultItem = {
  scene: SceneResultScene;
  analysis_artifact: SceneResultArtifact | null;
  evidence: SceneEvidenceItem[];
  illegal_evidence: { field_path: string; paragraph_id: string }[];
  revision: Record<string, unknown> | null;
};
export type RunResultsSummary = {
  total_scene_count: number;
  coverage_rate?: number | null;
  single_paragraph_scene_count: number;
  longest_scene_ordinal?: number | null;
  longest_scene_paragraph_count: number;
  manual_added_boundary_count: number;
  model_accepted_boundary_count: number;
  user_accepted_conflict_count: number;
  artifact_coverage_rate: number;
  evidence_coverage_rate: number;
  offline_recovered_scene_count: number;
};
export type RunResults = {
  run: {
    id: number;
    status: string;
    provider: string;
    model: string;
    prompt_version: string;
    schema_version: string;
    analysis_mode: string;
    execution_mode: string;
    completed_at?: string;
  };
  chapter: {
    id: number;
    book_id: number;
    chapter_index: number;
    title: string;
    display_title?: string | null;
  };
  boundary_revision: {
    id: number;
    revision_number: number;
    coverage_rate: number;
    confirmed_by: string;
    confirmed_at?: string;
  } | null;
  summary: RunResultsSummary;
  scenes: SceneResultItem[];
};

export type ReaderJourneyPreflight = {
  analysis_run_id: number;
  total_scenes: number;
  remaining_scenes: number;
  scene_batch_count: number;
  expected_requests: number;
  worst_case_requests: number;
  estimated_tokens: number;
  worst_case_tokens: number;
  estimated_cost: number;
  worst_case_cost: number;
  within_budget: boolean;
  exceeded_dimensions: string[];
  provider_state_version: string;
  provider_name: string;
  eligible: boolean;
  blockers: string[];
  requires_cloud_consent: boolean;
  currency: string;
  planner_version?: string | null;
  scene_prompt_version?: string | null;
  scene_contract_version?: string | null;
  batch_plan?: string[];
  recovery_mode?: boolean;
  existing_journey_run_id?: number | null;
};

export type ReaderJourneyProgress = {
  journey_run_id: number;
  analysis_run_id: number;
  status: string;
  current_stage?: string | null;
  total_scene_count: number;
  completed_scene_count: number;
  remaining_scene_count: number;
  completed_scene_ids: number[];
  remaining_scene_ids: number[];
  phase_count: number;
  has_chapter_summary: boolean;
  retryable: boolean;
  failed_stage?: string | null;
  root_error_code?: string | null;
  root_error_message?: string | null;
  failed_scene_id?: number | null;
  failed_scene_ordinal?: number | null;
  failed_invocation_id?: number | null;
  completed_at?: string | null;
  planner_version?: string | null;
  current_planner_version?: string | null;
  scene_prompt_version?: string | null;
  scene_contract_version?: string | null;
  recovery_safe?: boolean;
  blind_resume_blocked?: boolean;
  resume_block_reason?: string | null;
  reservation_released?: boolean;
  request_count?: number;
  total_tokens?: number;
  estimated_cost?: number;
  currency?: string;
  failure_details?: Record<string, unknown> | null;
  resume_preflight?: {
    remaining_scenes?: number;
    scene_batch_count?: number;
    batch_plan?: string[];
    expected_requests?: number;
    worst_case_requests?: number;
    estimated_tokens?: number;
    worst_case_tokens?: number;
    estimated_cost?: number;
    worst_case_cost?: number;
    planner_version?: string;
    currency?: string;
  } | null;
  user_error_message?: string | null;
  offline_replay_available?: boolean;
  offline_replayable_scene_count?: number;
  offline_replayable_invocation_ids?: number[];
  current_contract_version?: string | null;
  recoverable_contract_version?: string | null;
};

export type ReaderJourneyAccepted = {
  journey_run_id: number;
  status: string;
  existing_journey_run_id?: number | null;
  idempotent_replay?: boolean;
  recovery_recommended?: boolean;
  creation_blocked_reason?: string | null;
};

import type { ReaderJourneyVisualization } from "./readerJourneyVisualization";

export type ReaderJourneyResult = {
  journey_run_id: number;
  analysis_run_id: number;
  status: string;
  formula_version: string;
  scene_contract_version?: string | null;
  scene_prompt_version?: string | null;
  visualization?: ReaderJourneyVisualization | null;
  phases: {
    ordinal: number;
    title: string;
    start_scene_ordinal: number;
    end_scene_ordinal: number;
    primary_reader_question: string;
    summary: string;
  }[];
  scene_profiles: {
    scene_id: number;
    scene_ordinal: number;
    scene_value_summary: string;
    dominant_emotion: string;
    engagement: { engagement_score: number };
    reader_question_in: string[];
    reader_question_out: string[];
    payoffs: string[];
    hooks: string[];
    risk_points: string[];
    evidence_paragraph_ids: string[];
  }[];
  one_sentence_diagnosis?: string | null;
  deterministic_statistics?: {
    journey_nodes?: Array<{
      scene_id: number;
      scene_ordinal: number;
      paragraph_count: number;
      role: string;
      label?: string;
      primary_question?: string;
    }>;
    question_chains?: unknown[];
    [key: string]: unknown;
  } | null;
  scene_revision_id?: number | null;
  scene_boundary_hash?: string | null;
  result_status?: string | null;
  is_current?: boolean | null;
  is_superseded?: boolean | null;
  created_at?: string | null;
  completed_at?: string | null;
};
export type SceneParagraphs = {
  scene_id: number;
  scene_key: string;
  ordinal: number;
  start_paragraph_id: string;
  end_paragraph_id: string;
  paragraphs: {
    id: string;
    paragraph_index: number;
    raw_text: string;
    in_scene: boolean;
  }[];
};
export type Run = {
  id: number;
  subject_id: string;
  subject_type?: string;
  task_type?: string;
  book_id?: number | null;
  provider: string;
  model: string;
  status: string;
  progress_current: number;
  progress_total: number;
  execution_mode: string;
  cloud_consent: boolean;
  sends_content_to_cloud: boolean;
  error_code?: string;
  error_message?: string;
  root_error_code?: string;
  root_error_message?: string;
  failed_stage?: string;
  failed_invocation_id?: number;
  retryable: boolean;
  user_action_hint?: string;
  created_at: string;
  started_at?: string;
  completed_at?: string;
  status_version?: number;
  cancellation_requested_at?: string | null;
  cancelled_at?: string | null;
  cancellation_reason?: string | null;
  cancelled_by?: string | null;
  can_cancel?: boolean;
  can_restart_as_new_task?: boolean;
  budget_required?: { requests?: number; tokens?: number; estimated_cost?: number };
  budget_remaining?: { requests?: number; tokens?: number; estimated_cost?: number };
  exceeded_dimensions?: string[];
  reservation_status?: string;
  current_stage?: string;
  failure_details?: Record<string, unknown>;
  legacy_classification_warning?: boolean;
  exception_type?: string;
  transport_kind?: string;
  actual_failed_stage?: string;
  failed_invocation?: Record<string, unknown>;
  validation_error_code?: string;
  failed_transition_id?: string;
  failed_batch_index?: number;
  reusable_checkpoint_count: number;
  conflicted_checkpoint_count: number;
  checkpoint_total_count: number;
  checkpoint_available: boolean;
  recovered_from_run_id?: number;
  scene_analysis_resume_available?: boolean;
  detection_recovery_available?: boolean;
  remaining_detection_batch_count?: number;
  boundary_revision_id?: number;
  total_scene_count?: number;
  completed_scene_count?: number;
  remaining_scene_count?: number;
  failed_scene_id?: number;
  failed_scene_index?: number;
  historical_failed_scene_id?: number;
  historical_failed_scene_index?: number;
  historical_failed_invocation_id?: number;
  scene_analysis_coverage_rate?: number;
  offline_replay_available?: boolean;
  failed_scene_http_attempts?: number;
  scene_analysis_max_http_attempts?: number;
  completed_scene_ids?: number[];
  remaining_scene_ids?: number[];
  chapter_complete?: boolean;
  scene_pipeline_complete?: boolean;
  effective_status?: string | null;
  checkpoint_stage?: string | null;
  resume_stage?: string | null;
  journey_run_id?: number | null;
  journey_status?: string | null;
  journey_completed_scene_count?: number | null;
  journey_total_scene_count?: number | null;
  journey_retryable?: boolean | null;
  journey_result_available?: boolean;
  journey_error_code?: string | null;
  primary_action?: string | null;
  failure_substage?: string | null;
  failure_reason_code?: string | null;
  boundary_candidate_total?: number | null;
  boundary_candidate_completed?: number | null;
  boundary_batch_total?: number | null;
  boundary_batch_completed?: number | null;
  usage_invocation_count?: number | null;
  usage_input_tokens?: number | null;
  usage_output_tokens?: number | null;
  usage_total_tokens?: number | null;
  usage_estimated_cost?: number | null;
  usage_cost_unknown?: boolean;
  last_requested_output_tokens?: number | null;
  last_actual_output_tokens?: number | null;
  last_finish_reason?: string | null;
  truncation_attempt_count?: number | null;
  run_started_at?: string;
  scene_validation_detail?: {
    validation_error_message?: string;
    categories?: string[];
    allowed_paragraph_ids?: string[];
    illegal_evidence_ids?: Array<{ field_path: string; paragraph_id: string }>;
    key_actions_count?: number;
    offline_replay_eligible?: boolean;
    post_normalization_error?: string;
  };
};

export type BoundaryReviewDecision = {
  id: number;
  transition_id: string;
  left_paragraph_id: string;
  right_paragraph_id: string;
  model_candidate: boolean;
  model_boundary_candidate?: boolean;
  model_confidence: number;
  model_reason_code?: string;
  first_pass_json: string;
  adjudication_result?: string;
  review_priority: string;
  user_decision: string;
  user_reason?: string;
  final_boundary: boolean;
  semantic_conflict: boolean;
  conflict_code?: string;
  deterministic_legal?: boolean;
  deterministic_reason?: string;
  enum_snapshot_json: string;
  source_batch_index?: number;
  manual_reason_type?: string;
};
export type Provider = {
  capability_schema_version: "1c-a-2";
  name: string;
  default_model: string;
  capabilities: {
    enabled: boolean;
    default: boolean;
    manual_only: boolean;
    cloud: boolean;
    region?: string;
    structured_output_mode: string;
    sends_content_to_cloud: boolean;
    profile_name: string;
    supports_boundary_candidates: boolean;
    requires_boundary_review: boolean;
    automatic_boundary_routing: boolean;
  };
  configured: boolean;
  connected: boolean;
  healthy: boolean;
  running?: boolean;
  status: string;
  detail?: string;
  eligible_for_automatic_analysis: boolean;
  enabled: boolean;
  supports_boundary_candidates: boolean;
  requires_boundary_review: boolean;
  automatic_boundary_routing: boolean;
  manual_boundary_candidate_eligible: boolean;
  automatic_route_eligible: boolean;
  manual_short_task_eligible: boolean;
  manual_selection_blockers: string[];
  automatic_route_blockers: string[];
  allow_auto_route: boolean;
  workflow_prompts: {
    boundary_candidate: string;
    boundary_adjudication: string;
    scene_analysis: string;
    thinking: boolean;
    boundary_confirmation: string;
  } | null;
  eligibility_status: "eligible" | "blocked" | "unknown";
  evaluated_at: string;
  health_state: "healthy" | "unhealthy" | "unknown" | "stale";
  health_source: string;
  health_checked_at: string | null;
  provider_state_version: string;
};
export type Dashboard = {
  books: number;
  chapters: number;
  paragraphs: number;
  scenes: number;
  successful_runs: number;
  failed_runs: number;
  cloud_invocations: number;
  local_invocations: number;
};

export type ScenePartitionItem = {
  scene_order: number;
  start_paragraph_id: string;
  end_paragraph_id: string;
  included_in_journey: boolean;
};

export type SceneBoundaryRevisionSummary = {
  revision_id: number;
  revision_number: number;
  status: string;
  source: string;
  revision_etag: string;
  boundary_hash: string;
  chapter_text_hash: string;
  scenes: ScenePartitionItem[];
  confirmed_at?: string | null;
};

export type SceneBoundariesOverview = {
  chapter_id: number;
  chapter_text_hash: string;
  confirmed_revision: SceneBoundaryRevisionSummary | null;
  draft_revision: SceneBoundaryRevisionSummary | null;
  model_revision: SceneBoundaryRevisionSummary | null;
  awaiting_confirmation: boolean;
};

export type SceneBoundaryConfirmResponse = {
  revision_id: number;
  revision_etag: string;
  boundary_hash: string;
  journey_run_id: number | null;
  journey_started: boolean;
  journey_status?: string | null;
  already_confirmed?: boolean;
  journey_error_code?: string | null;
  journey_error_message?: string | null;
};
